### ISSUE TITLE
Remplacer Meteor par une vrai technologie web 

### ISSUE THREAD

**Issue by NitriKx** [superkebab/sjtvpc#1]
SVP

**Comment by serut** [comment]
OMG

Léo

2016-01-14 14:50 GMT+01:00 Benoît Sauvère <notifications@github.com>:

**Comment by NitriKx** [comment]
J'ai l'impression que l'issue a été closed sans avoir fait le travail. Je me trompe ?

**Comment by serut** [comment]
T'y connais rien go lire le guide http://guide.meteor.com/
Ce guide est sorti mardi

**Comment by NitriKx** [comment]
Ha OK.

**Comment by serut** [comment]
Tu lis le guide, tu me dis ce qui ne va pas, et après on se rappelle ;)

**Comment by julienCsj** [comment]
Je propose de passer a Play!

**Comment by superkebab** [comment]
Les télévangélistes de supermarché sont de sortie :/

**Comment by serut** [comment]
Tu t'es fais deface Benoit :-1:

**Comment by NitriKx** [comment]
Ha ha excellent @serut
